title: Tate | Security+ | CDSA | CCD | CCNA [loading...]
description: Entry-level SOC Analyst | Systems & Network Security Specialist
show_downloads: true
google_analytics: true
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
